// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// Sección: imports
// Este archivo contiene opciones generadas para inicializar Firebase por plataforma.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // Sección: selector por plataforma
  // Retorna la configuración correcta según el sistema operativo actual.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Sección: configuración Android
  // Credenciales y parámetros del app Android registrada en Firebase.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5aagSxLAn--yc0hbQOjqGyttUiz1Gx8E',
    appId: '1:1066844169526:android:c67d404728885c093f7f97',
    messagingSenderId: '1066844169526',
    projectId: 'vetcontrol-fb44b',
    storageBucket: 'vetcontrol-fb44b.firebasestorage.app',
  );

  // Sección: configuración iOS
  // Credenciales y parámetros del app iOS registrada en Firebase.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKwQQB89SeDVe37qmsp0jh8-TcJ555nWA',
    appId: '1:1066844169526:ios:1c473c81ad3909323f7f97',
    messagingSenderId: '1066844169526',
    projectId: 'vetcontrol-fb44b',
    storageBucket: 'vetcontrol-fb44b.firebasestorage.app',
    iosBundleId: 'com.example.petcontrolLimpio',
  );

  // Sección: configuración Web
  // Credenciales y parámetros del app web registrada en Firebase.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW690-4v3z5SNpFv7091KTcNR3k_2e3BY',
    appId: '1:1066844169526:web:1d38b2aa4cc3e9583f7f97',
    messagingSenderId: '1066844169526',
    projectId: 'vetcontrol-fb44b',
    authDomain: 'vetcontrol-fb44b.firebaseapp.com',
    storageBucket: 'vetcontrol-fb44b.firebasestorage.app',
    measurementId: 'G-RSGTM4XX4S',
  );
}
